---
name: react-workflow
on: 
  push: 
    branches: 
      - main 

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: checkout code
        uses: actions/checkout@v4
        
      - name: setup node.js
        uses: actions/setup-node@v4
        with: 
          node-version: 18.20.8

      - name: install dependencies
        run: npm install
        
      - name: build project
        run: npm build 
        
      - name: run tests 
        run : npm run test  
